#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# validate git branch name
local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)\/[a-zA-Z0-9\-]+)$'

message="There is something wrong with your branch name. Branch names in this project must adhere to this contract: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "$message"
    exit 1
fi

# TS type check
pnpm run typecheck

# check tests
pnpm test:ci
